### ISSUE TITLE
Performant image viewer

### ISSUE THREAD

**Issue by phyy-nx** [phyy-nx/SwissFEL#25]
- First examine dxtbx, 'get first pixel'.  Write a for loop and read a whole dataset, timing it.  No way the image viewer will go fast than this
- Profile wxPython/pyslip code and look for inefficiencies
- Consider re-writing nexus.py in C++ (assembling the dxtbx models from NeXus using h5py might be very inefficient)

**Comment by nksauter** [comment]
When paging through “Next” image within a Jungfrau 16M dataset there is considerable overhead for each image.
dials.image_viewer /net/dials/raid1/swissfel/p18163/res/Cyt/run_000795.JF07T32V01_master.h5

Performance was assessed both the Python cProfile module at the level of function calls, and line-by-line bisection with the libtbx/development Profiler.  Some performance barriers were considered too complex to address at this time:

1) _Image_ConvertToBitmap , within wx/core.py (largest time sink)
2) dataset_as_flex, with dxtbx/format/nexus.py
3) within dials/util/image_viewer/slip_viewer/tile_generation.py, the use of matrix_paste_block_in_place uses low-level std::copy and there is no clear way to make it more efficient.
4) within the followup_brightness_scale, our algorithm calls for evaluating the 90th-percentile of the data.  It would be desirable if a standard library function could be used such as std::nth_element, but this far less performant than the existing code.  Linking against the Intel math kernel library and/or offloading to GPU might be a future option.
5) in FlexImage::setZoom, the adjust() function has a complicated access pattern that is probably not optimal.
6) the prep_string function likewise has a complicated access pattern that is probably not optimal.
7) Allocating uninitialized flex doubles for “rawdata” in _get_flex_image_multipanel  does not actually save wall clock time

However, other code fragments were amenable to redesign, contributing measurable savings on overhead time:
1) Removal of the locals() function calls within tile_generation.py (0.75 sec/next image)
2) Two changes in followup_brightness_scale:
Use of af::mean scitbx library function instead of explicitly implemented mean. (save 0.14 sec/image)
Use pointer dereference instead of operator [], also refactor arithmetic, saving 0.19 sec/image. 
3) Use of init_functor_null to avoid initialization of channels array in two places:
FlexImage constructor for single-panel detectors, 0.9 sec/image on a 9Mpixel detector.
generic_flex_image constructor for Jungfrau 16M, saving 0.16 sec/image.

Final result is approx. 1.5 seconds overhead/image.
